# ./run_fmriprep.sh sub-02
./run_fmriprep.sh sub-03
./run_fmriprep.sh sub-04
./run_fmriprep.sh sub-05
./run_fmriprep.sh sub-06
./run_fmriprep.sh sub-07
./run_fmriprep.sh sub-08
./run_fmriprep.sh sub-09
./run_fmriprep.sh sub-10
./run_fmriprep.sh sub-11
./run_fmriprep.sh sub-12
./run_fmriprep.sh sub-13
./run_fmriprep.sh sub-14
./run_fmriprep.sh sub-15
./run_fmriprep.sh sub-16
./run_fmriprep.sh sub-17
./run_fmriprep.sh sub-18
./run_fmriprep.sh sub-19
./run_fmriprep.sh sub-20
./run_fmriprep.sh sub-21
./run_fmriprep.sh sub-22
./run_fmriprep.sh sub-23
./run_fmriprep.sh sub-24
./run_fmriprep.sh sub-25
./run_fmriprep.sh sub-26
./run_fmriprep.sh sub-27
./run_fmriprep.sh sub-28
./run_fmriprep.sh sub-29
./run_fmriprep.sh sub-30
./run_fmriprep.sh sub-31
./run_fmriprep.sh sub-32
./run_fmriprep.sh sub-33
./run_fmriprep.sh sub-34
./run_fmriprep.sh sub-35
./run_fmriprep.sh sub-36
./run_fmriprep.sh sub-37
./run_fmriprep.sh sub-38
./run_fmriprep.sh sub-39
./run_fmriprep.sh sub-40
./run_fmriprep.sh sub-41
./run_fmriprep.sh sub-42
./run_fmriprep.sh sub-43
./run_fmriprep.sh sub-44
./run_fmriprep.sh sub-45
./run_fmriprep.sh sub-46
./run_fmriprep.sh sub-47
./run_fmriprep.sh sub-48
./run_fmriprep.sh sub-49
./run_fmriprep.sh sub-50
./run_fmriprep.sh sub-51
./run_fmriprep.sh sub-52
./run_fmriprep.sh sub-53
./run_fmriprep.sh sub-54
./run_fmriprep.sh sub-55
./run_fmriprep.sh sub-56
./run_fmriprep.sh sub-57
./run_fmriprep.sh sub-58
./run_fmriprep.sh sub-59
./run_fmriprep.sh sub-60
./run_fmriprep.sh sub-61
./run_fmriprep.sh sub-62
./run_fmriprep.sh sub-63
./run_fmriprep.sh sub-64
./run_fmriprep.sh sub-65
./run_fmriprep.sh sub-66
./run_fmriprep.sh sub-67
./run_fmriprep.sh sub-68
./run_fmriprep.sh sub-69
./run_fmriprep.sh sub-70
./run_fmriprep.sh sub-71
./run_fmriprep.sh sub-72

# qbatch --options "-C bigmem" -w 30:00:00 fmriprep_batch_jobs.sh